### ISSUE TITLE
Checkpoints & more documentation

### ISSUE THREAD

**Issue by jsamson008** [jsedoc/SETC#1]
This awesome!

Can you send details as to where to locate the checkpoints, and elaborate the README?

**Comment by jsedoc** [comment]
The checkpoints are available at [http://chatbot-eval-data.s3-accelerate.amazonaws.com/results/available_checkpoints.txt](http://chatbot-eval-data.s3-accelerate.amazonaws.com/results/available_checkpoints.txt).

**Comment by jsedoc** [comment]
I've added this to the README file.
